---
# Common handlers
# File: common/handlers/main.yml
#

- name: start ntp
  service: "name={{ ntp_service_name }} state=started enabled=yes"
  sudo: yes
  tags: ntp

- name: restart ntp
  service: "name={{ ntp_service_name }} state=restarted enabled=yes"
  sudo: yes
  tags: ntp
