---
# Debian/Ubuntu specific
# file: common/tasks/Debian.yml

- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes

# Configure ntp + timezone
- name: Configuring timezone
  shell: "echo {{ host_timezone }} > /etc/timezone; dpkg-reconfigure --frontend noninteractive tzdata"
  tags: ntp

- apt:
    name: ntp
    state: present
  sudo: yes
  notify:
    - restart ntp
  tags: ntp

- name: Sync with ntp
  shell: "ntpdate -u {{ ntp_servers | random }}"
  sudo: yes
  tags: ntp

# Install tools
- name: Ensure the latest htop iotop vnstat nethogs is installed
  apt: 
    name: "{{ item }}"
    state: latest
  sudo: yes
  with_items:
    - htop
    - iotop
    - vnstat
    - nethogs
  tags: tools
