---
# Debian/Ubuntu specific
# file: tasks/Debian.yml

- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes

#- name: Ensure ntp is installed
- apt:
    name: ntp
    state: present
  sudo: yes
  notify:
    - restart ntp
  tags: ntp

- name: Sync with ntp
  shell: "ntpdate -u {{ ntp_servers | random }}"
  sudo: yes
  tags: ntp

- name: Ensure the latest htop iotop vnstat nethogs is installed
  apt: 
    name: "{{ item }}"
    state: latest
  sudo: yes
  with_items:
    - htop
    - iotop
    - vnstat
    - nethogs
  tags: tools
