---
# OS specific package installations
# File: common/tasks/main.yml
#

#- name: OS specific variables
#  include_vars: "{{ ansible_os_family }}.yml"

# tools installation
- include: "tools-{{ os_family }}.yml"

# ntp config
- include: "ntp-{{ os_family }}.yml"

# do the oracle_jdk work in a separate file
- include: "oracle_jdk-{{ os_family }}.yml"

