---
# NTP Config
# file: tasks/ntp-RedHat.yml

#- name: Ensure ntp is installed
- apt: name=ntp state=present
  tags: ntp

- name: Ensure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: Ensure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp
