---
# Oracle JDK
# File: common/tasks/oracle_jdk-Debian.yml
#

- name: Oracle JDK | Debian | Make sure the ansible required dependencies are installed
  apt:
    name: "{{item}}"
    state: present
  sudo: yes
  with_items: ["python-pycurl", "debconf", "debconf-utils"]
  tags: oracle_jdk

- name: Oracle JDK | Debian | Add webupd8 repository apt-key
  apt_key:
    url: "http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC2518248EEA14886"
    state: present
  sudo: yes
  tags: oracle_jdk

- name: Oracle JDK | Debian | Add webupd8 repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main'
    state: present
  sudo: yes
  tags: oracle_jdk

- name: Oracle JDK | Debian | Add webupd8 repository (src)
  apt_repository:
    repo: 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main'
    state: present
  sudo: yes
  tags: oracle_jdk

# Only for ansible 1.6 and higher...
- name: Oracle JDK | Debian | Accept Oracle license
  debconf:
    name: "{{item}}"
    question: "shared/accepted-oracle-license-v1-1"
    vtype: "select"
    value: "true"
  sudo: yes
  with_items:
    - oracle-java6-installer
    - oracle-java7-installer
    - oracle-java8-installer
  tags: oracle_jdk

- name: Oracle JDK | Debian | Install JDK package(s)
  apt:
    name: "oracle-java{{ oracle_jdk_java_versions }}-installer"
    state: present
    update_cache: yes
  sudo: yes
  tags: oracle_jdk

- name: Oracle JDK | Debian | Set the default Java version
  apt:
    name: "oracle-java{{ oracle_jdk_java_version_default }}-set-default"
    state: present
    update_cache: yes
  sudo: yes
  tags: oracle_jdk
