---
# Oracle JDK
# File: common/tasks/jdk-RedHat.yml
#

- name: Oracle JDK | RedHat | Checking if file download exists
  stat: "path={{ jdk_file_path }}"
  register: jdk_dl
  tags: oracle_jdk

# could do another check on md5 of file to force a download
- name: Oracle JDK | RedHat | Download from Oracle
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    "http://download.oracle.com/otn-pub/java/jdk/{{ java_version }}-{{ java_build }}/{{ jdk_file_name }}"
    -O {{ jdk_file_path }} creates={{ jdk_file_path }}'
  register: jdk_downloaded
  when: jdk_dl.stat.exists == false
  tags: oracle_jdk

- name: Oracle JDK | RedHat | Install RPM package
  yum: 
    name: "/tmp/jdk-{{ java_version }}-linux-x{{ ansible_userspace_bits }}.rpm"
    state: present
  register: jdk_installed
  when: jdk_dl.stat.exists == true or jdk_downloaded|changed
  tags: oracle_jdk

- name: Oracle JDK | RedHat | Set java link to latest
  command: alternatives --install /usr/bin/java java /usr/java/latest/bin/java 200000
  when: jdk_installed|changed
  tags: oracle_jdk

- name: Oracle JDK | RedHat | Set jar link to latest
  command: alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
  when: jdk_installed|changed
  tags: oracle_jdk

- name: Oracle JDK | RedHat | Update profile
  copy: src=java_env.sh dest=/etc/profile.d/java_env.sh
  when: jdk_installed|changed
  tags: oracle_jdk
