---
#
# File: elasticsearch/tasks/main.yml
#

#- name: OS specific variables
#  include_vars: "{{ ansible_os_family }}.yml" is not as safe as below
- include_vars: "Debian.yml"
  when: ansible_os_family == 'Debian'
  tags: vars

- include_vars: "RedHat.yml"
  when: ansible_os_family == 'RedHat'
  tags: vars


# Configure user and group
- name: Elasticsearch | Configuring user and group
  group: "name={{ es_group }}"
  tags: elasticsearch
- user: "name={{ es_user }} group={{ es_group }} createhome=no"
  tags: elasticsearch

# Check whether we have aleady installed the same version
- shell: "if [ -e /usr/share/elasticsearch/lib/elasticsearch-{{ es_version }}.jar ]; then echo yes; else echo no; fi;"
  register: version_exists
  always_run: True
  tags: elasticsearch

# Download install file if needed
- name: Elasticsearch | Download Elasticsearch
  get_url: "url={{ es_download_url }}/{{ es_dl_file_name }}.{{ es_dl_file_ext }} dest=/tmp/{{ es_dl_file_name }}.{{ es_dl_file_ext }} mode=0440"
  when: version_exists.stdout == 'no'
  tags: elasticsearch

- include_vars: "es-Debian.yml"
  when: ansible_os_family == 'Debian'
  tags: elasticsearch

- include_vars: "es-RedHat.yml"
  when: ansible_os_family == 'RedHat'
  tags: elasticsearch

# Configure Elasticsearch Node
- name: Elasticsearch | Configuring Elasticsearch Node
  template: "src=elasticsearch.yml.j2 dest={{ es_conf_dir }}/elasticsearch.yml owner={{ es_user }} group={{ es_group }} mode=0644"
  when: es_conf_dir is defined
  tags: elasticsearch
- template: "src=elasticsearch.defaults.j2 dest=/etc/{{ es_defaults_dir }}/elasticsearch owner={{ es_user }} group={{ es_group }} mode=0644"
  tags: elasticsearch

